trigger:
  branches:
    include:
    - master
  tags:
    include:
    - v*

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

- bash: |
    echo ">>> Compile ecosia-search-vscode-extension"
    npm i && npm run compile
    echo ">>> Compiled ecosia-search-vscode-extension"
    cd ecosia-search-vscode-extension
    echo ">>> Run integration test"
    npm i && npm run compile && npm run test
  displayName: Run Tests
  env:
    DISPLAY: ':99.0'